### ISSUE TITLE
improve readme

### ISSUE THREAD

**Issue by bradgarropy** [bradgarropy/gatsby-starter#16]
https://github.com/gatsbyjs/gatsby/pull/24734#issuecomment-660473546

**Comment by muescha** [comment]
> README.md: instructions for how to install and configure your starter, a list of its features or structure, and any helpful tips

https://www.gatsbyjs.org/docs/creating-a-starter/#basic-requirements

tip: you look at other starters for examples or the linked from docs: https://github.com/gatsbyjs/gatsby-starter-hello-world/

**Comment by bradgarropy** [comment]
Should be muuuuch better now @muescha!

https://github.com/bradgarropy/gatsby-starter#readme

**Comment by muescha** [comment]
👍 great
